CREATE TABLE dbo.Integrations (
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY
	,APIID INT NOT NULL
	,IntegrationName VARCHAR(50) NOT NULL
	,DatabaseName VARCHAR(128) NOT NULL
	,TableName VARCHAR(128) NOT NULL
)