CREATE TABLE dbo.RunLog (
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY
	,RunID UNIQUEIDENTIFIER NOT NULL
	,VendorID INT NULL
	,APIID INT NULL
	,IntegrationID INT NULL
	,LogDate DATETIME NULL DEFAULT GETDATE()
	,LogText VARCHAR(255) NOT NULL
	,APIURL VARCHAR(MAX) NULL
	,APIResponse VARCHAR(MAX) NULL
	,APIResultCount BIGINT NULL
	,SQLCode VARCHAR(MAX) NULL
	,SQLResultCount BIGINT NULL
	,IsFailure BIT NULL DEFAULT 0
)